version: "3"
services:
  student_db:
    image: postgres:13
    container_name: student_db
    restart: always #container reinicia se morrer
    ports:
      - 2345:5432
    env_file:
      - ./back-end/.env #configurar POSTGRES_USER, POSTGRES_PASSWORD e POSTGRES_DB
    volumes:
      - pg_students:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: ./back-end/ #Dockerfile do node se encontra na pasta atual
    ports:
      - 5000:5000
    depends_on:
      - student_db # só sobe quando o postgres tiver no ar
    env_file:
      - ./back-end/.env #configurar DATABASE_URL

  react_students: 
    container_name: react_students
    build: ./front-end
    volumes:
      - build_react:/var/www/html
    stdin_open: true

  nginx_students: 
    container_name: nginx_students
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - student_db
      - node_app
      - react_students


volumes:
  pg_students:
  build_react: